services:
  wedding-card:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: digital-wedding-card:latest
    container_name: digital-wedding-card
    ports:
      - "5989:80"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WEDDING_BRIDE: ${WEDDING_BRIDE:-}
      WEDDING_GROOM: ${WEDDING_GROOM:-}
      WEDDING_BRIDE_LAST_NAME: ${WEDDING_BRIDE_LAST_NAME:-}
      WEDDING_GROOM_LAST_NAME: ${WEDDING_GROOM_LAST_NAME:-}
      WEDDING_EVENT_TYPE: ${WEDDING_EVENT_TYPE:-}
      WEDDING_DAY_NAME: ${WEDDING_DAY_NAME:-}
      WEDDING_PERSIAN_DATE: ${WEDDING_PERSIAN_DATE:-}
      WEDDING_TIME: ${WEDDING_TIME:-}
      WEDDING_LOCATION_NAME: ${WEDDING_LOCATION_NAME:-}
      WEDDING_LOCATION_ADDRESS: ${WEDDING_LOCATION_ADDRESS:-}
      WEDDING_LATITUDE: ${WEDDING_LATITUDE:-}
      WEDDING_LONGITUDE: ${WEDDING_LONGITUDE:-}
      WEDDING_MESSAGE_INTRO: ${WEDDING_MESSAGE_INTRO:-}
      WEDDING_MESSAGE_COUPLE_NAMES: ${WEDDING_MESSAGE_COUPLE_NAMES:-}
      WEDDING_MESSAGE_BODY: ${WEDDING_MESSAGE_BODY:-}
      WEDDING_ENVELOPE_IMAGE: ${WEDDING_ENVELOPE_IMAGE:-}
      WEDDING_ENVELOPE_ALT: ${WEDDING_ENVELOPE_ALT:-}
      WEDDING_MUSIC_SRC: ${WEDDING_MUSIC_SRC:-}
      WEDDING_MUSIC_VOLUME: ${WEDDING_MUSIC_VOLUME:-}
      WEDDING_DECORATION: ${WEDDING_DECORATION:-}
